# Rewrite a path
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/aboutus"
  to = "/pages/aboutus.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/pages/projects.html"
  status = 200

[[redirects]]
  from = "/contactus"
  to = "/pages/contactus.html"
  status = 200