# Rewrite a path
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/pages/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/pages/aboutus"
  to = "/pages/aboutus.html"
  status = 200

[[redirects]]
  from = "/pages/projects"
  to = "/pages/projects.html"
  status = 200

[[redirects]]
  from = "/pages/contactus"
  to = "/pages/contactus.html"
  status = 200